const genreConfig=[{key:'drama',title:'드라마',en:'Drama'},{key:'thriller',title:'스릴러',en:'Thriller'},{key:'horror',title:'공포',en:'Horror'},{key:'action',title:'액션',en:'Action'},{key:'romance',title:'로맨스',en:'Romance'},{key:'melo',title:'멜로',en:'Melo'},{key:'experimental',title:'실험적인',en:'Experimental'},{key:'trailer',title:'예고편',en:'Trailer'}];
const DB_NAME='RTIO712_UPLOAD_DB_STABLE';const STORE='tracks';const MAX=50;let db;let state={activeGenre:'drama',tracks:{}};
const $=id=>document.getElementById(id);$('year').textContent=new Date().getFullYear();
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains(STORE)){d.createObjectStore(STORE,{keyPath:'id'});}};r.onsuccess=e=>res(e.target.result);r.onerror=()=>rej(r.error);});}
function readAll(){return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).getAll();req.onsuccess=()=>res(req.result||[]);req.onerror=()=>rej(req.error);});}
function putTrack(t){return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');const req=tx.objectStore(STORE).put(t);req.onsuccess=()=>res();req.onerror=()=>rej(req.error);});}
function deleteTrack(id){return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');const req=tx.objectStore(STORE).delete(id);req.onsuccess=()=>res();req.onerror=()=>rej(req.error);});}
function clearTracks(){return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');const req=tx.objectStore(STORE).clear();req.onsuccess=()=>res();req.onerror=()=>rej(req.error);});}
async function refresh(){const all=await readAll();state.tracks={};all.forEach(t=>{if(!state.tracks[t.genre])state.tracks[t.genre]=[];state.tracks[t.genre].push(t);});Object.keys(state.tracks).forEach(k=>state.tracks[k].sort((a,b)=>b.createdAt-a.createdAt));renderAll();}
function meta(k){return genreConfig.find(g=>g.key===k)||genreConfig[0];}
function esc(v){return String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');}
function audioURL(blob){return URL.createObjectURL(blob);}
function initOptions(){genreConfig.forEach(g=>{let o=document.createElement('option');o.value=g.key;o.textContent=`${g.title} / ${g.en}`;$('genreSelect').appendChild(o);});}
function renderStatus(){let el=$('statusInline');el.innerHTML='';genreConfig.forEach(g=>{let c=(state.tracks[g.key]||[]).length;let d=document.createElement('div');d.className='status-chip';d.innerHTML=`<strong>${g.title}</strong><span>${c} / ${MAX}</span>`;el.appendChild(d);});}
function renderCards(){let el=$('genreCards');el.innerHTML='';genreConfig.forEach(g=>{let list=state.tracks[g.key]||[];let latest=list[0];let card=document.createElement('article');card.className=`genre-card${state.activeGenre===g.key?' active':''}`;let html=`<div class="genre-top"><div><div class="genre-title">${g.title}</div><span class="genre-sub">${g.en}</span></div><div class="genre-count">${list.length} / ${MAX}</div></div><div class="latest-wrap"><span class="latest-label">Latest Upload</span>`;if(latest){html+=`<div class="latest-title">${esc(latest.title)}</div><div class="latest-file">${esc(latest.fileName)}</div><audio controls preload="none" src="${audioURL(latest.blob)}"></audio>`;}else{html+=`<div class="genre-empty">아직 업로드된 트랙이 없습니다.<br>아래 Upload Studio에서 추가해 주세요.</div>`;}html+='</div>';card.innerHTML=html;card.addEventListener('click',()=>{state.activeGenre=g.key;renderAll();document.querySelector('.genre-view-shell').scrollIntoView({behavior:'smooth',block:'start'});});el.appendChild(card);});}
function renderList(){let g=meta(state.activeGenre),list=state.tracks[state.activeGenre]||[];$('activeGenreLabel').textContent=`${g.title} / ${g.en}`;$('activeGenreTitle').textContent=`${g.title} 장르 트랙 라이브러리`;$('activeGenreCount').textContent=`${list.length} / ${MAX} Tracks`;let el=$('trackList');el.innerHTML='';if(!list.length){el.innerHTML=`<div class="empty-banner">${g.title} 장르에는 아직 업로드된 파일이 없습니다.<br>Upload Studio에서 파일을 추가해 주세요.</div>`;return;}list.forEach((t,i)=>{let row=document.createElement('article');row.className='track-row';row.innerHTML=`<div class="slot">Track ${String(i+1).padStart(2,'0')}</div><div class="title">${esc(t.title)}</div><div class="file">${esc(t.fileName)}</div><div><audio controls preload="none" src="${audioURL(t.blob)}"></audio></div><div><button class="btn btn-light" type="button">삭제</button></div>`;row.querySelector('button').addEventListener('click',async()=>{await deleteTrack(t.id);await refresh();});el.appendChild(row);});}
function renderAll(){renderStatus();renderCards();renderList();}
$('addTrackBtn').addEventListener('click',async()=>{let genre=$('genreSelect').value,title=$('trackTitle').value.trim(),file=$('audioFile').files&&$('audioFile').files[0];if(!genre)return alert('장르를 선택해 주세요.');if(!title)return alert('트랙 제목을 입력해 주세요.');if(!file)return alert('오디오 파일을 선택해 주세요.');let count=(state.tracks[genre]||[]).length;if(count>=MAX)return alert('이 장르는 최대 50곡까지만 업로드할 수 있습니다.');await putTrack({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),genre,title,fileName:file.name,type:file.type,blob:file,createdAt:Date.now()});$('trackTitle').value='';$('audioFile').value='';state.activeGenre=genre;await refresh();document.getElementById('genre-library').scrollIntoView({behavior:'smooth',block:'start'});});
$('clearAllBtn').addEventListener('click',async()=>{if(confirm('전체 업로드 데이터를 삭제하시겠습니까?')){await clearTracks();await refresh();}});
(async()=>{db=await openDB();initOptions();await refresh();})();
